begin;

alter table public.review_intelligence_findings
  add column if not exists finding_order integer,
  add column if not exists processed_at timestamptz not null default now(),
  add column if not exists intensity_score numeric,
  add column if not exists severity_score numeric,
  add column if not exists confidence numeric,
  add column if not exists impact_score numeric,
  add column if not exists prompt_version text,
  add column if not exists model_version text;

update public.review_intelligence_findings f
set finding_order = numbered.finding_order
from (
  select id,
         row_number() over (
           partition by imported_review_id
           order by created_at nulls last, id
         )::integer as finding_order
  from public.review_intelligence_findings
  where finding_order is null
) numbered
where f.id = numbered.id;

alter table public.review_intelligence_findings
  alter column finding_order set not null;

alter table public.review_intelligence_findings
  drop constraint if exists review_intelligence_findings_finding_order_check,
  add constraint review_intelligence_findings_finding_order_check
    check (finding_order >= 1),
  drop constraint if exists review_intelligence_findings_intensity_score_check,
  add constraint review_intelligence_findings_intensity_score_check
    check (intensity_score is null or intensity_score between 0 and 1),
  drop constraint if exists review_intelligence_findings_severity_score_check,
  add constraint review_intelligence_findings_severity_score_check
    check (severity_score is null or severity_score between 0 and 1),
  drop constraint if exists review_intelligence_findings_confidence_check,
  add constraint review_intelligence_findings_confidence_check
    check (confidence is null or confidence between 0 and 1),
  drop constraint if exists review_intelligence_findings_impact_score_check,
  add constraint review_intelligence_findings_impact_score_check
    check (impact_score is null or impact_score between 0 and 1);

create unique index if not exists uq_review_findings_review_order
  on public.review_intelligence_findings(imported_review_id, finding_order);

create table if not exists public.review_finding_relationships (
  id bigint generated by default as identity primary key,
  root_finding_id bigint not null
    references public.review_intelligence_findings(id) on delete cascade,
  connected_finding_id bigint not null
    references public.review_intelligence_findings(id) on delete cascade,
  connector text not null,
  relationship_type text not null,
  connector_position integer,
  notes text,
  created_at timestamptz not null default now(),
  constraint review_finding_relationships_distinct_findings
    check (root_finding_id <> connected_finding_id),
  constraint review_finding_relationships_connector_position_check
    check (connector_position is null or connector_position >= 0),
  constraint review_finding_relationships_type_check
    check (relationship_type in (
      'contrast', 'concession', 'addition', 'exception', 'cause',
      'effect', 'condition', 'comparison', 'sequence', 'emphasis',
      'clarification', 'alternative', 'unknown'
    ))
);

create index if not exists idx_review_finding_relationships_root
  on public.review_finding_relationships(root_finding_id);
create index if not exists idx_review_finding_relationships_connected
  on public.review_finding_relationships(connected_finding_id);
create index if not exists idx_review_finding_relationships_type
  on public.review_finding_relationships(relationship_type);

create or replace function public.replace_review_understanding(
  p_imported_review_id bigint,
  p_findings jsonb,
  p_relationships jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_finding jsonb;
  v_relationship jsonb;
  v_finding_id bigint;
  v_root_id bigint;
  v_connected_id bigint;
  v_saved_findings jsonb := '[]'::jsonb;
  v_saved_relationships jsonb := '[]'::jsonb;
begin
  if p_imported_review_id is null or p_imported_review_id <= 0 then
    raise exception 'A valid imported review ID is required.';
  end if;
  if jsonb_typeof(coalesce(p_findings, '[]'::jsonb)) <> 'array' then
    raise exception 'p_findings must be a JSON array.';
  end if;
  if jsonb_typeof(coalesce(p_relationships, '[]'::jsonb)) <> 'array' then
    raise exception 'p_relationships must be a JSON array.';
  end if;

  delete from public.review_intelligence_findings
  where imported_review_id = p_imported_review_id;

  for v_finding in
    select value from jsonb_array_elements(coalesce(p_findings, '[]'::jsonb))
    order by (value->>'finding_order')::integer
  loop
    insert into public.review_intelligence_findings (
      imported_review_id, finding_order, area_code, cause_code,
      subcause_code, sentiment, sentiment_score, intensity_score,
      severity_score, confidence, impact_score, finding_summary,
      evidence_text, operational_priority, requires_response,
      processed_at, prompt_version, model_version, raw_ai_output
    ) values (
      p_imported_review_id,
      (v_finding->>'finding_order')::integer,
      nullif(v_finding->>'area_code', ''),
      nullif(v_finding->>'cause_code', ''),
      nullif(v_finding->>'subcause_code', ''),
      v_finding->>'sentiment',
      nullif(v_finding->>'sentiment_score', '')::numeric,
      (v_finding->>'intensity_score')::numeric,
      (v_finding->>'severity_score')::numeric,
      (v_finding->>'confidence')::numeric,
      (v_finding->>'impact_score')::numeric,
      v_finding->>'finding_summary',
      v_finding->>'evidence_text',
      v_finding->>'operational_priority',
      coalesce((v_finding->>'requires_response')::boolean, false),
      coalesce((v_finding->>'processed_at')::timestamptz, now()),
      nullif(v_finding->>'prompt_version', ''),
      nullif(v_finding->>'model_version', ''),
      v_finding->'raw_ai_output'
    ) returning id into v_finding_id;

    v_saved_findings := v_saved_findings || jsonb_build_array(
      jsonb_build_object(
        'id', v_finding_id,
        'imported_review_id', p_imported_review_id,
        'finding_order', (v_finding->>'finding_order')::integer
      )
    );
  end loop;

  for v_relationship in
    select value from jsonb_array_elements(coalesce(p_relationships, '[]'::jsonb))
  loop
    select id into v_root_id
    from public.review_intelligence_findings
    where imported_review_id = p_imported_review_id
      and finding_order = (v_relationship->>'root_finding_order')::integer;

    select id into v_connected_id
    from public.review_intelligence_findings
    where imported_review_id = p_imported_review_id
      and finding_order = (v_relationship->>'connected_finding_order')::integer;

    if v_root_id is null or v_connected_id is null then
      raise exception 'Relationship references an unknown finding_order.';
    end if;

    insert into public.review_finding_relationships (
      root_finding_id, connected_finding_id, connector,
      relationship_type, connector_position, notes
    ) values (
      v_root_id,
      v_connected_id,
      v_relationship->>'connector',
      v_relationship->>'relationship_type',
      nullif(v_relationship->>'connector_position', '')::integer,
      nullif(v_relationship->>'notes', '')
    ) returning id into v_finding_id;

    v_saved_relationships := v_saved_relationships || jsonb_build_array(
      jsonb_build_object(
        'id', v_finding_id,
        'root_finding_id', v_root_id,
        'connected_finding_id', v_connected_id
      )
    );
  end loop;

  return jsonb_build_object(
    'findings', v_saved_findings,
    'relationships', v_saved_relationships
  );
end;
$$;

commit;
